apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbc-outbound
  labels:
    app: sbc-outbound
{{ include "common.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: sbc-outbound
  template:
    metadata:
      labels:
        app: sbc-outbound
    spec:
      initContainers:
        - image: kanisterio/mysql-sidecar:0.40.0
          name: db-create-wait
          command:
            - sh 
            - -c 
            - |
              until mysql -u {{ .Values.mysql.user }} -D {{ .Values.mysql.database }} -h mysql.{{ default .Release.Namespace .Values.global.db.namespace }} -p${MYSQL_PASSWORD} --protocol=tcp -e "select count(*) from accounts";
              do 
                sleep 5
              done
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: MYSQL_PASSWORD
      containers:
        - name: sbc-outbound
          image: {{ .Values.sbcOutbound.image }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.sbcOutbound.imagePullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/opt/app/bin/k8s-pre-stop-hook.js"]
          ports:
            - name: dtmf
              containerPort: 22225
              protocol: UDP
            - name: health
              containerPort: 3000
              protocol: UDP
            - name: drachtio
              containerPort: {{ .Values.sbcInbound.drachtioPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: K8S 
              value: "1"
            - name: JAMBONES_LOGLEVEL
              value: info
            - name: DRACHTIO_PORT
              value: {{ .Values.sbcOutbound.drachtioPort | quote }}
            - name: DTMF_LISTEN_PORT
              value: "22225"
            - name: K8S_RTPENGINE_SERVICE_NAME 
              value: "rtpengine-ng:22222"
            - name: JAMBONES_TIME_SERIES_HOST 
              value: influxdb.{{ default .Release.Namespace .Values.global.monitoring.namespace }}
            - name: JAMBONES_REDIS_HOST
              value: redis.{{ default .Release.Namespace .Values.global.db.namespace }}
            - name: JAMBONES_REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: ENABLE_METRICS
              value: {{ default "0" .Values.stats.enabled  | quote }}
            {{- if .Values.stats.enabled }}
            - name: STATS_HOST
              value: {{ .Values.stats.host }}.{{ default .Release.Namespace .Values.global.monitoring.namespace }}
            - name: STATS_PORT
              value: {{ .Values.stats.port  | quote }}
            - name: STATS_PROTOCOL
              value: {{ .Values.stats.protocol }}
            - name: STATS_TELEGRAF
              value: "1"
            - name: STATS_SAMPLE_RATE
              value:  {{ .Values.stats.sampleRate | quote }}
            {{- end }}
            - name: JAMBONES_MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: JAMBONES_MYSQL_HOST
              value: mysql.{{ default .Release.Namespace .Values.global.db.namespace }}
            - name: JAMBONES_MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: JAMBONES_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: MYSQL_PASSWORD
            - name: DRACHTIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: DRACHTIO_SECRET
      terminationGracePeriodSeconds: 900
