apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer-webapp
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  rules:
    - host: {{ required "hostname for the homer portal" .Values.homer.hostname }}
      http:
        paths:
        - backend:
            service:
              name: homer-webapp
              port: 
                number: 80
          path: /
          pathType: Prefix

